-- =============================================================================
-- REATIVADOS - Scripts SQL Utilitarios
-- Base: BD_BENEFICIOS_HIST.dbo.REATIVADOS
-- object_id = 853578079 | 104 campos
-- =============================================================================

-- 1. PROFILING GERAL
SELECT COUNT(*) AS total_registros,
       COUNT(DISTINCT NU_NB) AS nb_unicos,
       COUNT(DISTINCT ANO_MES_REF) AS competencias,
       MIN(ANO_MES_REF) AS competencia_min,
       MAX(ANO_MES_REF) AS competencia_max
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS];

SELECT ANO_MES_REF,
       COUNT(*) AS total,
       ROUND(AVG(VL_MR_ATU), 2) AS media_valor,
       ROUND(SUM(VL_MR_ATU), 2) AS soma_valor
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
GROUP BY ANO_MES_REF
ORDER BY ANO_MES_REF;

SELECT CS_SIT_BENEF_ANT,
       CS_SITUACAO_BENEF,
       COUNT(*) AS qtd
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
GROUP BY CS_SIT_BENEF_ANT, CS_SITUACAO_BENEF
ORDER BY qtd DESC;

-- 2. INTEGRIDADE E CONSISTENCIA
SELECT NU_NB, ANO_MES_REF, COUNT(*) AS cnt
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
GROUP BY NU_NB, ANO_MES_REF
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS situacao_atual_fora_dominio
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS] r
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_SITUACAO] s ON CAST(r.CS_SITUACAO_BENEF AS varchar(5)) = s.COD_SITUACAO
WHERE r.CS_SITUACAO_BENEF IS NOT NULL AND s.COD_SITUACAO IS NULL;

SELECT COUNT(*) AS situacao_anterior_fora_dominio
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS] r
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_SITUACAO] s ON CAST(r.CS_SIT_BENEF_ANT AS varchar(5)) = s.COD_SITUACAO
WHERE r.CS_SIT_BENEF_ANT IS NOT NULL AND s.COD_SITUACAO IS NULL;

SELECT COUNT(*) AS acao_sem_motivo
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
WHERE D2_ACAO IS NOT NULL AND D2_ACAO <> ''
  AND CS_MOTIVO_ACAO IS NULL;

SELECT COUNT(*) AS formato_d2_efetivacao_invalido
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
WHERE D2_EFETIVACAO IS NOT NULL AND D2_EFETIVACAO <> ''
  AND LEN(D2_EFETIVACAO) <> 6;

-- 3. ANALISE DE DOMINIOS
SELECT r.CS_ESPECIE,
       e.DESCR_ESPECIE,
       COUNT(*) AS qtd
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS] r
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_ESPECIE] e ON CAST(r.CS_ESPECIE AS varchar(5)) = e.COD_ESPECIE
GROUP BY r.CS_ESPECIE, e.DESCR_ESPECIE
ORDER BY qtd DESC;

SELECT r.CS_TIPO_R,
       t.DESCR_TIPO,
       COUNT(*) AS qtd
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS] r
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_TIPO] t ON CAST(r.CS_TIPO_R AS varchar(5)) = t.COD_TIPO
GROUP BY r.CS_TIPO_R, t.DESCR_TIPO
ORDER BY qtd DESC;

SELECT CS_CLIENTELA,
       COUNT(*) AS qtd,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER(), 2) AS pct
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
GROUP BY CS_CLIENTELA;

-- 4. CONSULTAS REUTILIZAVEIS
SELECT r.NU_NB,
       r.ANO_MES_REF,
       r.CS_ESPECIE,
       e.DESCR_ESPECIE,
       r.CS_SIT_BENEF_ANT,
       s1.DESCR_SITUACAO AS descr_situacao_anterior,
       r.CS_SITUACAO_BENEF,
       s2.DESCR_SITUACAO AS descr_situacao_atual,
       r.D2_ACAO,
       r.D2_EFETIVACAO,
       r.CS_MOTIVO_ACAO,
       r.NM_TITULAR_BENEF_T,
       r.NM_RECEBEDOR,
       r.NM_REPRESENTANTE_R,
       r.NM_ARQUIVO
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS] r
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_ESPECIE] e ON CAST(r.CS_ESPECIE AS varchar(5)) = e.COD_ESPECIE
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_SITUACAO] s1 ON CAST(r.CS_SIT_BENEF_ANT AS varchar(5)) = s1.COD_SITUACAO
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_SITUACAO] s2 ON CAST(r.CS_SITUACAO_BENEF AS varchar(5)) = s2.COD_SITUACAO;

SELECT NU_NB,
       ANO_MES_REF,
       CASE WHEN LEN(D2_ACAO) = 8 THEN CONVERT(date, SUBSTRING(D2_ACAO,5,4)+SUBSTRING(D2_ACAO,3,2)+SUBSTRING(D2_ACAO,1,2)) END AS data_acao,
       D2_EFETIVACAO,
       CS_SIT_BENEF_ANT,
       CS_SITUACAO_BENEF,
       CS_MOTIVO_ACAO
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS];

SELECT NU_NB,
       ANO_MES_REF,
       NM_TITULAR_BENEF_T,
       NM_REPRESENTANTE_R,
       NU_CPF_R,
       CS_TIPO_R
FROM [BD_BENEFICIOS_HIST].[dbo].[REATIVADOS]
WHERE (NM_REPRESENTANTE_R IS NOT NULL AND NM_REPRESENTANTE_R <> '')
   OR (NU_CPF_R IS NOT NULL AND NU_CPF_R <> '00000000000');
