-- =============================================================================
-- PAB - Scripts SQL Utilitarios
-- Base: BD_BENEFICIOS_HIST.dbo.PAB
-- object_id = 837578022 | 100 campos
-- =============================================================================

-- 1. PROFILING GERAL
SELECT COUNT(*) AS total_registros,
       COUNT(DISTINCT NU_NB) AS nb_unicos,
       COUNT(DISTINCT ANO_MES_REF) AS competencias,
       MIN(ANO_MES_REF) AS competencia_min,
       MAX(ANO_MES_REF) AS competencia_max
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB];

SELECT ANO_MES_REF,
       COUNT(*) AS total,
       ROUND(SUM(VL_LIQUIDO_CRED), 2) AS soma_credito,
       ROUND(AVG(VL_LIQUIDO_CRED), 2) AS media_credito
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
GROUP BY ANO_MES_REF
ORDER BY ANO_MES_REF;

SELECT CS_ESPECIE, COUNT(*) AS qtd
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
GROUP BY CS_ESPECIE
ORDER BY qtd DESC;

-- 2. INTEGRIDADE E CONSISTENCIA
SELECT NU_NB, ANO_MES_REF, COUNT(*) AS cnt
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
GROUP BY NU_NB, ANO_MES_REF
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS datas_invalidas
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
WHERE (D2_SOLIC_CREDITO IS NOT NULL AND D2_SOLIC_CREDITO <> '' AND LEN(D2_SOLIC_CREDITO) <> 8)
   OR (D2_VALIDACAO_CRED IS NOT NULL AND D2_VALIDACAO_CRED <> '' AND LEN(D2_VALIDACAO_CRED) <> 8)
   OR (D2_INI_PERIODO IS NOT NULL AND D2_INI_PERIODO <> '' AND LEN(D2_INI_PERIODO) <> 8)
   OR (D2_FIM_PERIODO IS NOT NULL AND D2_FIM_PERIODO <> '' AND LEN(D2_FIM_PERIODO) <> 8);

SELECT COUNT(*) AS periodo_invalido
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
WHERE LEN(D2_INI_PERIODO) = 8 AND LEN(D2_FIM_PERIODO) = 8
  AND CONVERT(date, SUBSTRING(D2_INI_PERIODO,5,4)+SUBSTRING(D2_INI_PERIODO,3,2)+SUBSTRING(D2_INI_PERIODO,1,2))
    > CONVERT(date, SUBSTRING(D2_FIM_PERIODO,5,4)+SUBSTRING(D2_FIM_PERIODO,3,2)+SUBSTRING(D2_FIM_PERIODO,1,2));

SELECT p.CS_SITUACAO_BENEF, COUNT(*) AS cnt
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB] p
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_SITUACAO] s ON CAST(p.CS_SITUACAO_BENEF AS varchar(5)) = s.COD_SITUACAO
WHERE s.COD_SITUACAO IS NULL AND p.CS_SITUACAO_BENEF IS NOT NULL
GROUP BY p.CS_SITUACAO_BENEF;

-- 3. ANALISE DE DOMINIOS
SELECT p.CS_ESPECIE,
       e.DESCR_ESPECIE,
       COUNT(*) AS qtd,
       ROUND(SUM(p.VL_LIQUIDO_CRED), 2) AS soma_credito
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB] p
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_ESPECIE] e ON CAST(p.CS_ESPECIE AS varchar(5)) = e.COD_ESPECIE
GROUP BY p.CS_ESPECIE, e.DESCR_ESPECIE
ORDER BY qtd DESC;

SELECT p.CS_MEIO_PAGTO,
       mp.DESCR_MEIO_PAGAMENTO,
       COUNT(*) AS qtd
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB] p
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_MEIO_PAGAMENTO] mp ON CAST(p.CS_MEIO_PAGTO AS varchar(5)) = mp.COD_MEIO_PAGAMENTO
GROUP BY p.CS_MEIO_PAGTO, mp.DESCR_MEIO_PAGAMENTO
ORDER BY qtd DESC;

SELECT CS_CLIENTELA,
       COUNT(*) AS qtd,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER(), 2) AS pct
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
GROUP BY CS_CLIENTELA;

-- 4. CONSULTAS REUTILIZAVEIS
SELECT p.NU_NB,
       p.ANO_MES_REF,
       p.CS_ESPECIE,
       e.DESCR_ESPECIE,
       p.CS_SITUACAO_BENEF,
       s.DESCR_SITUACAO,
       p.VL_RMI,
       p.VL_SB,
       p.VL_LIQUIDO_CRED,
       p.D2_SOLIC_CREDITO,
       p.D2_VALIDACAO_CRED,
       p.D2_INI_PERIODO,
       p.D2_FIM_PERIODO,
       p.NM_TITULAR_BENEF_T,
       p.NM_RECEBEDOR_PAB,
       p.NM_ARQUIVO
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB] p
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_ESPECIE] e ON CAST(p.CS_ESPECIE AS varchar(5)) = e.COD_ESPECIE
LEFT JOIN [BD_BENEFICIOS_HIST].[dbo].[COD_SITUACAO] s ON CAST(p.CS_SITUACAO_BENEF AS varchar(5)) = s.COD_SITUACAO;

SELECT NU_NB,
       ANO_MES_REF,
       VL_LIQUIDO_CRED,
       CASE WHEN LEN(D2_SOLIC_CREDITO) = 8 THEN CONVERT(date, SUBSTRING(D2_SOLIC_CREDITO,5,4)+SUBSTRING(D2_SOLIC_CREDITO,3,2)+SUBSTRING(D2_SOLIC_CREDITO,1,2)) END AS data_solicitacao,
       CASE WHEN LEN(D2_VALIDACAO_CRED) = 8 THEN CONVERT(date, SUBSTRING(D2_VALIDACAO_CRED,5,4)+SUBSTRING(D2_VALIDACAO_CRED,3,2)+SUBSTRING(D2_VALIDACAO_CRED,1,2)) END AS data_validacao
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB];

SELECT NU_NB,
       ANO_MES_REF,
       CS_MOTIVO_SOLIC,
       CS_ORIGEM_CREDITO,
       VL_LIQUIDO_CRED,
       NM_RECEBEDOR_PAB
FROM [BD_BENEFICIOS_HIST].[dbo].[PAB]
WHERE VL_LIQUIDO_CRED > 0
ORDER BY VL_LIQUIDO_CRED DESC;
