-- ====================================================
-- PESSOA - Scripts SQL utilitarios
-- Base: BD_CAD_UNICO.dbo.PESSOA
-- ====================================================

-- 1. PROFILING GERAL
SELECT COUNT(*) AS total_registros,
       COUNT(DISTINCT COD_PESSOA) AS pessoas_unicas,
       COUNT(DISTINCT COD_FAMILIA) AS familias_unicas,
       COUNT(DISTINCT NUM_NIS_PESSOA_ATUAL) AS nis_unicos,
       MIN(ANO_MES_CARGA) AS competencia_min,
       MAX(ANO_MES_CARGA) AS competencia_max
FROM [BD_CAD_UNICO].[dbo].[PESSOA];

SELECT ANO_MES_CARGA, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[PESSOA]
GROUP BY ANO_MES_CARGA
ORDER BY ANO_MES_CARGA;

SELECT COD_SEXO_PESSOA, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[PESSOA]
GROUP BY COD_SEXO_PESSOA
ORDER BY qtd DESC;

-- 2. INTEGRIDADE REFERENCIAL E REGRAS
SELECT p.COD_FAMILIA, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
LEFT JOIN [BD_CAD_UNICO].[dbo].[FAMILIA] f ON p.COD_FAMILIA = f.COD_FAMILIA
WHERE p.COD_FAMILIA IS NOT NULL AND f.COD_FAMILIA IS NULL
GROUP BY p.COD_FAMILIA;

SELECT p.COD_PARENTESCO_RF_PESSOA, COUNT(*) AS qtd_sem_dominio
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_PARENTESCO] d ON p.COD_PARENTESCO_RF_PESSOA = d.COD
WHERE p.COD_PARENTESCO_RF_PESSOA IS NOT NULL AND d.COD IS NULL
GROUP BY p.COD_PARENTESCO_RF_PESSOA;

SELECT COUNT(*) AS inconsistencias_data
FROM [BD_CAD_UNICO].[dbo].[PESSOA]
WHERE DTA_ATUAL_MEMB < DTA_CADASTRAMENTO_MEMB;

-- 3. ANALISE DE DOMINIOS
SELECT p.COD_SEXO_PESSOA, s.DESCR, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_SEXO_PESSOA] s ON p.COD_SEXO_PESSOA = s.COD
GROUP BY p.COD_SEXO_PESSOA, s.DESCR
ORDER BY qtd DESC;

SELECT p.COD_PARENTESCO_RF_PESSOA, d.DESCR, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_PARENTESCO] d ON p.COD_PARENTESCO_RF_PESSOA = d.COD
GROUP BY p.COD_PARENTESCO_RF_PESSOA, d.DESCR
ORDER BY qtd DESC;

SELECT p.COD_RACA_COR_PESSOA, r.DESCR, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_RACA] r ON p.COD_RACA_COR_PESSOA = r.COD
GROUP BY p.COD_RACA_COR_PESSOA, r.DESCR
ORDER BY qtd DESC;

-- 4. CONSULTAS REUTILIZAVEIS
SELECT p.COD_PESSOA,
       p.COD_FAMILIA,
       p.NOM_PESSOA,
       p.NUM_NIS_PESSOA_ATUAL,
       p.COD_SEXO_PESSOA,
       sx.DESCR AS DESCR_SEXO,
       p.DTA_NASC_PESSOA,
       p.COD_PARENTESCO_RF_PESSOA,
       pr.DESCR AS DESCR_PARENTESCO,
       p.COD_RACA_COR_PESSOA,
       rc.DESCR AS DESCR_RACA,
       p.ANO_MES_CARGA
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_SEXO_PESSOA] sx ON p.COD_SEXO_PESSOA = sx.COD
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_PARENTESCO] pr ON p.COD_PARENTESCO_RF_PESSOA = pr.COD
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_RACA] rc ON p.COD_RACA_COR_PESSOA = rc.COD;

SELECT p.COD_FAMILIA,
       COUNT(*) AS qtd_membros,
       SUM(CASE WHEN p.COD_PARENTESCO_RF_PESSOA = '01' THEN 1 ELSE 0 END) AS qtd_responsavel_familiar
FROM [BD_CAD_UNICO].[dbo].[PESSOA] p
GROUP BY p.COD_FAMILIA
ORDER BY qtd_membros DESC;
