-- ====================================================
-- FAMILIA - Scripts SQL utilitarios
-- Base: BD_CAD_UNICO.dbo.FAMILIA
-- ====================================================

-- 1. PROFILING GERAL
SELECT COUNT(*) AS total_registros,
       COUNT(DISTINCT COD_FAMILIA) AS familias_unicas,
       COUNT(DISTINCT COD_PREFEITURA) AS prefeituras,
       MIN(ANO_MES_CARGA) AS competencia_min,
       MAX(ANO_MES_CARGA) AS competencia_max
FROM [BD_CAD_UNICO].[dbo].[FAMILIA];

SELECT ANO_MES_CARGA, COUNT(*) AS qtd, AVG(VLR_RENDA_MEDIA_FAM) AS media_renda
FROM [BD_CAD_UNICO].[dbo].[FAMILIA]
GROUP BY ANO_MES_CARGA
ORDER BY ANO_MES_CARGA;

SELECT COD_EST_CADASTRAL_FAM, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[FAMILIA]
GROUP BY COD_EST_CADASTRAL_FAM
ORDER BY qtd DESC;

-- 2. INTEGRIDADE REFERENCIAL E REGRAS
SELECT f.COD_EST_CADASTRAL_FAM, COUNT(*) AS qtd_sem_dominio
FROM [BD_CAD_UNICO].[dbo].[FAMILIA] f
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_EST_CADASTRAL_FAM] d ON f.COD_EST_CADASTRAL_FAM = d.COD
WHERE f.COD_EST_CADASTRAL_FAM IS NOT NULL AND d.COD IS NULL
GROUP BY f.COD_EST_CADASTRAL_FAM;

SELECT f.COD_CONDICAO_CADASTRO_FAM, COUNT(*) AS qtd_sem_dominio
FROM [BD_CAD_UNICO].[dbo].[FAMILIA] f
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_CONDICAO_CADASTRO_FAM] d ON f.COD_CONDICAO_CADASTRO_FAM = d.COD
WHERE f.COD_CONDICAO_CADASTRO_FAM IS NOT NULL AND d.COD IS NULL
GROUP BY f.COD_CONDICAO_CADASTRO_FAM;

SELECT COUNT(*) AS inconsistencias_data
FROM [BD_CAD_UNICO].[dbo].[FAMILIA]
WHERE DAT_ATUAL_FAM < DAT_CADASTRAMENTO_FAM;

-- 3. ANALISE DE DOMINIOS
SELECT f.COD_EST_CADASTRAL_FAM, d.DESCR, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[FAMILIA] f
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_EST_CADASTRAL_FAM] d ON f.COD_EST_CADASTRAL_FAM = d.COD
GROUP BY f.COD_EST_CADASTRAL_FAM, d.DESCR
ORDER BY qtd DESC;

SELECT f.COD_FORMA_COLETA_FAM, d.DESCR, COUNT(*) AS qtd
FROM [BD_CAD_UNICO].[dbo].[FAMILIA] f
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_FORMA_COLETA_FAM] d ON f.COD_FORMA_COLETA_FAM = d.COD
GROUP BY f.COD_FORMA_COLETA_FAM, d.DESCR
ORDER BY qtd DESC;

-- 4. CONSULTAS REUTILIZAVEIS
SELECT f.COD_FAMILIA,
       f.COD_PREFEITURA,
       f.COD_EST_CADASTRAL_FAM,
       ecf.DESCR AS DESCR_EST_CADASTRAL,
       f.COD_CONDICAO_CADASTRO_FAM,
       ccf.DESCR AS DESCR_CONDICAO,
       f.VLR_RENDA_MEDIA_FAM,
       f.DAT_CADASTRAMENTO_FAM,
       f.DAT_ATUAL_FAM,
       f.ANO_MES_CARGA
FROM [BD_CAD_UNICO].[dbo].[FAMILIA] f
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_EST_CADASTRAL_FAM] ecf ON f.COD_EST_CADASTRAL_FAM = ecf.COD
LEFT JOIN [BD_CAD_UNICO].[dbo].[COD_CONDICAO_CADASTRO_FAM] ccf ON f.COD_CONDICAO_CADASTRO_FAM = ccf.COD;

SELECT f.COD_FAMILIA,
       COUNT(p.COD_PESSOA) AS qtd_pessoas,
       MIN(p.DTA_NASC_PESSOA) AS menor_data_nasc,
       MAX(p.DTA_NASC_PESSOA) AS maior_data_nasc
FROM [BD_CAD_UNICO].[dbo].[FAMILIA] f
LEFT JOIN [BD_CAD_UNICO].[dbo].[PESSOA] p ON p.COD_FAMILIA = f.COD_FAMILIA
GROUP BY f.COD_FAMILIA
ORDER BY qtd_pessoas DESC;
